enable_damage = false
creative_mode = true
gameid = minetest
world_name = Minetest Classroom
auth_backend = sqlite3
backend = sqlite3
player_backend = sqlite3
load_mod_morelights = true
load_mod_university = true
load_mod_morelights_vintage = true
load_mod_morelights_extras = true
load_mod_morelights_modern = true
server_announce = false
load_mod_skinsdb = true
